---
- hosts: 172.31.13.77
  become: yes
  tasks:

  - include_tasks: Create_file.yml

  - name: Install webserver on Ubuntu
    apt:
     name: apache2
     state: present
    notify: restartwebserver

  - name: Copying myindex.j2 to node side
    template:
     src: myindex.j2
     dest: /var/www/html/index.html
    notify: restartwebserver


  handlers:
  - name: restartwebserver
    service:
     name: apache2
     state: restarted
