---
- hosts: 172.31.13.77
  become: yes
  tasks:

  - include_tasks: Files.yml

  - name: Install webserver on Ubuntu
    apt:
     name: apache2
     state: present

  - name: Copying myindex.j2 to node side
    template:
     src: myindex.j2
     dest: /var/www/html/index.html
