---
- hosts: localhost
  become: yes
  tasks:
  - name: Creating AWS instance using ansible
    ec2:
     key_name: DevOps
     instance_type: t2.micro
     image: ami-0f2e255ec956ade7f
     wait: yes
     group: MyIP
     count: 2
     region: ap-south-1
     vpc_subnet_id: subnet-04690a1f3092add50
     assign_public_ip: yes
