---
- hosts: 172.31.13.77
  become: yes
  tasks:

  - name: I want to execute linux command directly
    command: hostname1
    register: myresult

  - name: I want to display value of command
    debug:
     msg: "{{myresult}}"

  - name: Installing git
    apt:
     name: git 
     state: present
    when: myresult.stderr == ""

  - name: Installing tree
    apt:
     name: tree
     state: present
    when: myresult.stderr != ""
