---
- hosts: all
  become: yes
  tasks: 
  - name: Install webserver on Debain only
    apt:
     name: apache2
     state: present
    when: ansible_os_family == "Debian"

  - name: Install webserver on RedHat only
    yum:
     name: httpd
     state: present
    when: ansible_os_family == "RedHat"