---
- hosts: WebServer
  become: yes
  tasks:

  - name: Install webserver on Debian node only
    apt:
     name: "{{Package_for_Ubuntu}}"
     state: present
    when: ansible_os_family == "Debian"

  - name: Start webserver on Debian node
    service:
     name: "{{Package_for_Ubuntu}}"
     state: started
    when: ansible_os_family == "Debian"

  - name: Install webserver on RedHat node only
    yum:
     name: "{{Package_for_RedHat}}"
     state: present
    when: ansible_os_family == "RedHat"

  - name: Start webserver on Debian node
    service:
     name: "{{Package_for_RedHat}}"
     state: started
    when: ansible_os_family == "RedHat"