
- name: Deploying java application on ubuntu node
  get_url:
    url: https://get.jenkins.io/war-stable/2.332.1/jenkins.war
    dest: /opt/tomcat/webapps
    force_basic_auth: yes

- name: Deploying MahaLogin application on ubuntu node
  get_url:
    url: http://3.108.52.132:8082/artifactory/SIT_Branch/com/maha/mahaLogin/5.0/mahaLogin-5.0.war
    dest: /opt/tomcat/webapps
    force_basic_auth: yes