
  - name: Download Tomcat war file
    get_url:
     url: https://dlcdn.apache.org/tomcat/tomcat-8/v8.5.78/bin/apache-tomcat-8.5.78.tar.gz
     dest: /tmp/apache-tomcat-8.5.78.tar.gz
     force_basic_auth: yes

  - name: Create tomcat folder
    file:
     path: /opt/tomcat
     state: directory
     mode: '0755'

  - name: Extract Tomcat war file
    unarchive:
     src: /tmp/apache-tomcat-8.5.78.tar.gz
     dest: /opt/tomcat
     extra_opts: [--strip-components=1]
     remote_src: yes
