
- name: Create a systemd Service File
  template:
    src: systemd.j2
    dest: /etc/systemd/system/tomcat.service

- name: Reaload Deamon
  systemd:   
   daemon_reexec: yes
   name: tomcat

- name: Tomcat restart
  systemd:
   name: tomcat
   state: started
   enabled: yes