
- name: Create a systemd Service File
  template:
    src: systemd.j2
    dest: /etc/systemd/system/tomcat.service

- name: Reaload Deamon
  systemd:   
   daemon_reexec: yes
   name: tomcat
   enabled: yes

- name: Tomcat restart
  systemd:
   name: tomcat
   state: restarted

- name: Status tomcat
  command: sudo systemctl status tomcat
  register: tomcatstatus
- name: Tomcat status
  debug:
   msg: "{{tomcatstatus}}"
   