---
- hosts: 172.31.3.113
  tasks:

  - name: Update permissions on tomcat folder
    file:
     path: /opt/tomcat/
     owner: tomcat
     group: tomcat
     state: directory
     recurse: yes
     mode: '0777'